---
title: "lobster_exploration"
author: "Brooke Grazda"
date: "2024-08-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
```

```{r}
lobsters <- read_csv(here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", "")) |> 
  clean_names() |> 
  uncount(count)

lobster_count <- lobsters |> 
 group_by(site, year) |> 
  summarize(individuals = n(), mean_carapace = mean(size_mm, na.rm = TRUE)) |> 
  ungroup()

lobster_2020 <- lobsters |> 
  filter(year == 2020) |> 
  mutate(legal = case_when(size_mm >= 79.67~"yes", size_mm < 79.67~"no")) |> 
  group_by(site, legal) |> 
  summarize(individuals  = n())
  
 ex_a <- lobsters |> filter(site %in% c("IVEE", "CARP", "NAPL")) 
  
ex_b <- lobsters |> filter(month == 8) 

ex_c <-lobsters |> 
   filter(site == "AQUE" | size_mm > 70)

ex_d <- lobsters |> 
  filter(!site == "NAPL")
   
ex_e <- lobsters |> group_by(site) |> 
  summarise(mean(size_mm, na.rm = TRUE), sd(size_mm, na.rm = TRUE))

ex_f <- lobsters |> group_by(site, month) |> 
  summarise(max(size_mm, na.rm = TRUE))

ex_g <- lobsters |> 
  mutate(size_cm = size_mm / 10)

ex_h <- lobsters |> 
  mutate(lower_site = tolower(site))

ex_i <- lobsters |> mutate(as.character(area))

ex_j <- lobsters |> 
  mutate(size_bin = case_when(size_mm <= 70~"small", size_mm >70~"large"))

ex_k <- lobsters |> 
  mutate(designation = case_when(.default = "Not MPA", site %in% c("IVEE", "NAPL")~"MPA"))
```


```{r}
ggplot(lobster_count, aes(x = year,
                          y = individuals)) +
  geom_line(aes(group = site, color = site)) +
  theme_classic()
```


```{r}
ggplot(lobster_2020, aes(x =site, y = individuals, fill = legal)) +
  geom_col(position = "fill") +
  theme_minimal()
```




